test: Add SDK test for all mint operations
kin-labs/kinetic pull request #342
Opened 2022-07-10 05:01 UTC by RamirezAlex

2022-09-05 20:45 UTC, RamirezAlex commented
@beeman the tests pass in local env. but I am not sure how to add and enable the mint in the environment that we use for CI. Other than that, it should fine for review.

2022-09-05 21:26 UTC, beeman commented
> @beeman the tests pass in local env. but I am not sure how to add and enable the mint in the environment that we use for CI. Other than that, it should fine for review. Do you have any suggestions?

That makes sense. I think it's something that would be addressed by #285 - I'm going to pull this branch in and test if that makes it work and implement that.

2022-09-19 14:38 UTC, beeman requested changes
@RamirezAlex two small comments on this one.

2022-09-19 14:38 UTC, beeman commented on apps/sdk-e2e/src/integration/transaction-kinetic-sdk-e2e.spec.ts
> +    setTimeout(async () => {
We want to get rid of this `setTimeout`

2022-09-19 14:38 UTC, beeman commented on apps/sdk-e2e/src/integration/transaction-kinetic-sdk-e2e.spec.ts
> +      console.dir(tx, { depth: null })
Rogue logging

2022-09-19 14:41 UTC, beeman commented
@RamirezAlex make sure to pull in the branch before working on it. I added a way to run the sdk-e2e against the local API (without spinning up its own) which makes debugging easier.

```
yarn nx run sdk-e2e:e2e-local --verbose --watch
```

2022-09-19 22:45 UTC, beeman approved these changes

2022-09-19 22:45 UTC, merged